env: production
settings:
 timezone: "America/Toronto"
 touchbase-recurrence: "RRULE:FREQ=WEEKLY;"

# Here you update your contact list with their names.
# e.g.
# contacts:
# - name: Smally
# - name: Dad
# 
contacts:

# Here you add the different groups you'd like to have for your
# contacts. And populate each group with 
# each contact's id(i.e. index of their record in contacts)
# e.g. 
# groups:
#   friends:
#     - 0
#     - 1
#   family:
#     - 2
# 
groups:


# This section is automatically updated by the CLI App to manage
# events created by kronus
events: