contacts:
- name: Smally
- name: Dad
- name: Bro
- name: Doe
- name: Curry
- name: Aubrey
- name: Glen
- name: Lewis
events: []
groups:
  family:
  - 0
  - 1
  large-group:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
owner:
  email: test@gmail.com
secrets:
  google_application_credentials: Test
settings:
  timezone: America/Toronto
  touchbase-recurrence: RRULE:FREQ=WEEKLY;
