contacts:
- name: Smally
- name: Dad
- name: Bro
- name: Doe
- name: Curry
- name: Aubrey
- name: Glen
- name: Lewis
env: production
events: []
groups:
  family:
  - 0
  - 1
  large-group:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
settings:
  timezone: America/Toronto
  touchbase-recurrence: RRULE:FREQ=WEEKLY;
